Repository moevm/mse1h2025-xv6, pull requests merged in 2025-02, with the labels that each got.

#12 generating reports based on results #4
  scripts/generate_report.py
Labels: python

#8 create base Docker image #2
  README.md
  docker/.env
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker.md
  docker/requirements.txt
  docker/script.sh
Labels: docker

#10 Configure Makefile for Docker Management #9
  doсker/Makefile
  doсker/makedocker.md
Labels: documentation, docker

#13 fix Configure Makefile for Docker Management #9
  docker/Makefile
  docker/makedocker.md
Labels: documentation, docker

#11 A stub script for running a timeout check #5
  scripts/run_tests.py
  scripts/test.log
  solution/solution.py
Labels: python

#15 preliminary file checks before launch #3
  scripts/file_checker.py
Labels: python

#17 #14-preparation-of-presentation-materials
  reports.md
  reports/Презентация_1_итерация.pdf
Labels: documentation
