Repository moevm/mse1h2025-xv6, pull requests merged in 2025-04, with the labels that each got.

#55 #53 Fix script behavior run.sh in case of an error in trivial checks
  scripts/run.sh
Labels: bug

#56 Generating a report from logs #48
  scripts/file_checker.py
  scripts/generate_report.py
  scripts/load.py
  scripts/run.sh
  scripts/run_tests.py
Labels: enhancement, python

#61 51-Configuring-Docker-with-security-in-mind
  docker/Dockerfile
  docker/docker-compose.yml
Labels: enhancement, docker

#64 Create a step-by-step setup guide for running the project in Docker #58
  README.md
  Starting laboratory work manually/Lab. Copy-on-Write Fork for xv6/grade-lab-cow
  Starting laboratory work manually/Lab. Xv6 and Unix utilities/2. sleep/sleep.c
  Starting laboratory work manually/Lab. Xv6 and Unix utilities/3. pingpong/pingpong.c
  Starting laboratory work manually/Lab. Xv6 and Unix utilities/4. primes/primes.c
  Starting laboratory work manually/Lab. Xv6 and Unix utilities/5. find/find.c
  Starting laboratory work manually/Lab. Xv6 and Unix utilities/6. xargs/xargs.c
  Starting laboratory work manually/Lab. Xv6 and Unix utilities/grade-lab-util
  Starting laboratory work manually/Lab. file system/grade-lab-fs
  Starting laboratory work manually/Lab. locks/grade-lab-lock
  Starting laboratory work manually/Lab. mmap/grade-lab-mmap
  Starting laboratory work manually/Lab. networking/grade-lab-net
  Starting laboratory work manually/Lab. page tables/grade-lab-pgtbl
  Starting laboratory work manually/Lab. system calls/grade-lab-syscall
  Starting laboratory work manually/Lab. traps/grade-lab-traps
  Starting laboratory work manually/gradelib.py
  docker/makedocker.md
Labels: documentation
