Repository moevm/mse1h2025-xv6, pull requests merged in 2025-05, with the labels that each got.

#66 #49 Configure CI/CD for a Docker image
  .github/workflows/cicd.yml
Labels: docker, CI/CD

#68 Fix: consolidate logs and clamp score output #67
  scripts/file_checker.py
  scripts/generate_report.py
  scripts/load.py
  scripts/run.sh
  scripts/run_tests.py
Labels: enhancement

#63 #52 Test Development
  .github/workflows/tests.yml
  scripts/file_checker.py
  scripts/generate_report.py
  scripts/load.py
  scripts/run.sh
  tests/functional/test_file_checker.py
  tests/functional/test_load.py
  tests/integration/test_workflow.py
Labels: CI/CD, test

#72 #71 Error launching the Docker container due to incorrect line endings in scripts
  .gitattributes
Labels: enhancement
