Repository moevm/mse1h2025-xv6, pull requests merged in 2025-03, with the labels that each got.

#30 Writing unit tests for loading and launching scripts #22
  tests/test_downloader.py
  tests/test_integration.py
  tests/test_lab_runner.py
  tests/test_menu_interface.py
  tests/test_patcher.py
Labels: python, test

#31 #23 Developing a script for downloading, unzipping, and applying a patch
  scripts/load.py
Labels: python

#35 #34 Refactor script according to design mockup and update log folder path
  run.sh
Labels: enhancement

#39 #38 Change file_checker script logic to check files
  scripts/file_checker.py
Labels: enhancement

#36 #33 Integrate Existing Scripts into Docker Container
  docker/Dockerfile
  docker/Makefile
  docker/docker-compose.yml
  docker/docker.md
  docker/makedocker.md
  docker/requirements.txt
  docker/script.sh
Labels: docker

#44 #40 Migrate logging to the logging module
  scripts/run_tests.py
Labels: bug, enhancement, python

#46 Launching unit tests #37
  tests/pictures/test_downloader.png
  tests/pictures/test_integration.png
  tests/pictures/test_lab_runner.png
  tests/pictures/test_menu_interface.png
  tests/pictures/test_patcher.png
  tests/results.md
  tests/test_downloader.py
  tests/test_integration.py
  tests/test_lab_runner.py
  tests/test_menu_interface.py
  tests/test_patcher.py
Labels: python, test
